export const data = {
  products: [
    {
      name: "Nike Slim shirt 1",
      slug: "nike-slim-shirt-1",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Nike Slim shirt 2",
      slug: "nike-slim-shirt-2",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Nike Slim shirt 3",
      slug: "nike-slim-shirt-3",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 140,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
  ],
};
